title: mattboldt.com
github_username: mattboldt
github_url: http://github.com/mattboldt
highlighter: rouge
permalink: /:year/:month/:day/:title/
year: 2017
description: Matt Boldt
url: http://mattboldt.com
encoding: UTF-8

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end
sass:
  sass_dir: ./assets/css

paginate: 6
paginate_path: /page/:num/
